In [1]:
import tensorflow as tf
from matplotlib import pyplot as plt
import pickle
from tensorflow.keras.models import load_model
from tensorflow.math import confusion_matrix
from helper import data_import, relabel

In [2]:
train_path='./Group_10/train'
test_path='./Group_10/test'
val_path='./Group_10/val'

# All of these are lists. Images are not of same shape, hence can't have np.array()
x_train, y_train = data_import(train_path)
x_test, y_test = data_import(test_path)
x_val, y_val = data_import(val_path)

y_train = relabel(y_train)
y_test = relabel(y_test)
y_val = relabel(y_val)

# Architechture 1

In [3]:
model = load_model("./models/architecture1.h5")
model.summary()

Metal device set to: Apple M2

systemMemory: 8.00 GB
maxCacheSize: 2.67 GB

Model: "Architecture1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 224, 224, 3)]     0         
                                                                 
 rescaling (Rescaling)       (None, 224, 224, 3)       0         
                                                                 
 conv2d (Conv2D)             (None, 54, 54, 8)         2912      
                                                                 
 conv2d_1 (Conv2D)           (None, 50, 50, 16)        3216      
                                                                 
 max_pooling2d (MaxPooling2D  (None, 24, 24, 16)       0         
 )                                                               
                                                                 
 flatten (Flatten)           (None, 9216)  

2023-04-27 11:03:31.720245: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-04-27 11:03:31.720340: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [4]:
print("Train loss and accuracy for architechture 1:")
loss, acc = model.evaluate(x_train, y_train, verbose=0)
y_pdfs = model(x_train)
y_pred = tf.argmax(y_pdfs, axis=1)
print(f"Loss {loss:.4f}")
print(f"Accuracy: {acc:.4f}")
print(confusion_matrix(y_train, y_pred).numpy())

Train loss and accuracy for architechture 1:


2023-04-27 11:03:31.939227: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2023-04-27 11:03:32.049788: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Loss 0.0005
Accuracy: 1.0000
[[50  0  0  0  0]
 [ 0 50  0  0  0]
 [ 0  0 50  0  0]
 [ 0  0  0 50  0]
 [ 0  0  0  0 50]]


In [5]:
print("Validation loss and accuracy for architechture 1:")
loss, acc = model.evaluate(x_val, y_val, verbose=0)
y_pdfs = model(x_val)
y_pred = tf.argmax(y_pdfs, axis=1)
print(f"Loss {loss:.4f}")
print(f"Accuracy: {acc:.4f}")
print(confusion_matrix(y_val, y_pred).numpy())

Validation loss and accuracy for architechture 1:
Loss 1.0656
Accuracy: 0.8000
[[10  0  0  0  0]
 [ 0  7  1  0  2]
 [ 1  1  7  1  0]
 [ 1  1  2  6  0]
 [ 0  0  0  0 10]]


In [6]:
print("Test loss and accuracy for architechture 1:")
loss, acc = model.evaluate(x_test, y_test, verbose=0)
y_pdfs = model(x_test)
y_pred = tf.argmax(y_pdfs, axis=1)
print(f"Loss {loss:.4f}")
print(f"Accuracy: {acc:.4f}")
print("Confusion matrix:")
print(confusion_matrix(y_test, y_pred).numpy())

Test loss and accuracy for architechture 1:
Loss 0.9637
Accuracy: 0.7900
Confusion matrix:
[[17  2  0  0  1]
 [ 0 17  0  1  2]
 [ 1  2 16  1  0]
 [ 0  1  2 15  2]
 [ 0  6  0  0 14]]


# Architechture 2

In [7]:
model = load_model("./models/architecture2.h5")
model.summary()

Model: "Architecture2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 224, 224, 3)]     0         
                                                                 
 rescaling (Rescaling)       (None, 224, 224, 3)       0         
                                                                 
 conv2d (Conv2D)             (None, 54, 54, 8)         2912      
                                                                 
 conv2d_1 (Conv2D)           (None, 50, 50, 16)        3216      
                                                                 
 conv2d_2 (Conv2D)           (None, 48, 48, 32)        4640      
                                                                 
 max_pooling2d (MaxPooling2D  (None, 23, 23, 32)       0         
 )                                                               
                                                     

In [8]:
print("Train loss and accuracy for architechture 2:")
loss, acc = model.evaluate(x_train, y_train, verbose=0)
y_pdfs = model(x_train)
y_pred = tf.argmax(y_pdfs, axis=1)
print(f"Loss {loss:.4f}")
print(f"Accuracy: {acc:.4f}")
print(confusion_matrix(y_train, y_pred).numpy())

Train loss and accuracy for architechture 2:


2023-04-27 11:03:32.801566: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Loss 0.0005
Accuracy: 1.0000
[[50  0  0  0  0]
 [ 0 50  0  0  0]
 [ 0  0 50  0  0]
 [ 0  0  0 50  0]
 [ 0  0  0  0 50]]


In [9]:
print("Validation loss and accuracy for architechture 2:")
loss, acc = model.evaluate(x_val, y_val, verbose=0)
y_pdfs = model(x_val)
y_pred = tf.argmax(y_pdfs, axis=1)
print(f"Loss {loss:.4f}")
print(f"Accuracy: {acc:.4f}")
print(confusion_matrix(y_val, y_pred).numpy())

Validation loss and accuracy for architechture 2:
Loss 0.9502
Accuracy: 0.8400
[[10  0  0  0  0]
 [ 0  7  1  0  2]
 [ 0  0  7  1  2]
 [ 0  1  0  9  0]
 [ 0  0  1  0  9]]


In [10]:
print("Test loss and accuracy for architechture 2:")
loss, acc = model.evaluate(x_test, y_test, verbose=0)
y_pdfs = model(x_test)
y_pred = tf.argmax(y_pdfs, axis=1)
print(f"Loss {loss:.4f}")
print(f"Accuracy: {acc:.4f}")
print("Confusion matrix:")
print(confusion_matrix(y_test, y_pred).numpy())

Test loss and accuracy for architechture 2:
Loss 1.1578
Accuracy: 0.7600
Confusion matrix:
[[17  2  0  0  1]
 [ 0 15  0  1  4]
 [ 1  2 16  1  0]
 [ 1  1  2 14  2]
 [ 0  5  0  1 14]]


# Architechture 3

In [11]:
model = load_model("./models/architecture3.h5")
model.summary()

Model: "Architecture3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 224, 224, 3)]     0         
                                                                 
 rescaling (Rescaling)       (None, 224, 224, 3)       0         
                                                                 
 conv2d (Conv2D)             (None, 54, 54, 8)         2912      
                                                                 
 conv2d_1 (Conv2D)           (None, 50, 50, 16)        3216      
                                                                 
 conv2d_2 (Conv2D)           (None, 48, 48, 32)        4640      
                                                                 
 conv2d_3 (Conv2D)           (None, 46, 46, 64)        18496     
                                                                 
 max_pooling2d (MaxPooling2D  (None, 22, 22, 64)     

In [12]:
print("Train loss and accuracy for architechture 3:")
loss, acc = model.evaluate(x_train, y_train, verbose=0)
y_pdfs = model(x_train)
y_pred = tf.argmax(y_pdfs, axis=1)
print(f"Loss {loss:.4f}")
print(f"Accuracy: {acc:.4f}")
print(confusion_matrix(y_train, y_pred).numpy())

Train loss and accuracy for architechture 3:


2023-04-27 11:03:33.606593: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Loss 0.0006
Accuracy: 1.0000
[[50  0  0  0  0]
 [ 0 50  0  0  0]
 [ 0  0 50  0  0]
 [ 0  0  0 50  0]
 [ 0  0  0  0 50]]


In [13]:
print("Validation loss and accuracy for architechture 3:")
loss, acc = model.evaluate(x_val, y_val, verbose=0)
y_pdfs = model(x_val)
y_pred = tf.argmax(y_pdfs, axis=1)
print(f"Loss {loss:.4f}")
print(f"Accuracy: {acc:.4f}")
print(confusion_matrix(y_val, y_pred).numpy())

Validation loss and accuracy for architechture 3:
Loss 0.9665
Accuracy: 0.8200
[[10  0  0  0  0]
 [ 0  8  1  0  1]
 [ 1  0  7  1  1]
 [ 0  1  1  8  0]
 [ 0  2  0  0  8]]


In [14]:
print("Test loss and accuracy for architechture 3:")
loss, acc = model.evaluate(x_test, y_test, verbose=0)
y_pdfs = model(x_test)
y_pred = tf.argmax(y_pdfs, axis=1)
print(f"Loss {loss:.4f}")
print(f"Accuracy: {acc:.4f}")
print("Confusion matrix:")
print(confusion_matrix(y_test, y_pred).numpy())

Test loss and accuracy for architechture 3:
Loss 1.2955
Accuracy: 0.7600
Confusion matrix:
[[17  2  0  0  1]
 [ 0 16  1  1  2]
 [ 1  0 17  1  1]
 [ 0  1  3 15  1]
 [ 1  7  0  1 11]]
