In [18]:
import tensorflow as tf
from tensorflow.keras import layers, Sequential, Input, Model
import numpy as np

In [19]:
samples, timesteps, features = 32, 10, 8
inputs = np.random.random([50, 10, 4]).astype(np.float32)
simple_rnn = layers.SimpleRNN(4)

outputs = simple_rnn(inputs)
outputs.shape

TensorShape([50, 4])

In [53]:
samples, timesteps, features = 32, 50, 8
X, seq_lengths = [], []
for i in range(samples):
    l = np.random.randint(20, 50)
    X.append(np.random.random((l,features)))
    seq_lengths.append(l)

seq_lengths = np.array(seq_lengths)
Y = np.random.randint(3, size=samples)

In [54]:
max_len = np.max(seq_lengths)

In [55]:
seq_lengths[:10], max_len

(array([41, 26, 45, 27, 38, 48, 30, 22, 33, 25]), 49)

In [63]:
X_padded = tf.keras.utils.pad_sequences(X, value=10_000, padding="post", dtype=np.float64, maxlen=timesteps)


In [64]:
X_padded.shape

(32, 50, 8)

In [65]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Masking(mask_value=10_000, input_shape=(None, features)))
model.add(tf.keras.layers.SimpleRNN(32))
model.add(tf.keras.layers.Dense(3))

model.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 masking_9 (Masking)         (None, None, 8)           0         
                                                                 
 simple_rnn_11 (SimpleRNN)   (None, 32)                1312      
                                                                 
 dense_8 (Dense)             (None, 3)                 99        
                                                                 
Total params: 1,411
Trainable params: 1,411
Non-trainable params: 0
_________________________________________________________________


In [66]:
model(np.expand_dims(X[0], 0))

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[ 0.07405048, -0.19711518, -0.76090425]], dtype=float32)>

In [67]:
model(np.expand_dims(X_padded[0], 0))

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[ 0.07405048, -0.19711518, -0.76090425]], dtype=float32)>

In [75]:
model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])

In [76]:
model.fit(X_padded, Y, batch_size=1, epochs=50, verbose=2)


Epoch 1/50
32/32 - 1s - loss: 1.0986 - accuracy: 0.3125 - 615ms/epoch - 19ms/step
Epoch 2/50
32/32 - 0s - loss: 1.0986 - accuracy: 0.3125 - 74ms/epoch - 2ms/step
Epoch 3/50
32/32 - 0s - loss: 1.0986 - accuracy: 0.3125 - 70ms/epoch - 2ms/step
Epoch 4/50
32/32 - 0s - loss: 1.0986 - accuracy: 0.3125 - 69ms/epoch - 2ms/step
Epoch 5/50
32/32 - 0s - loss: 1.0986 - accuracy: 0.3125 - 70ms/epoch - 2ms/step
Epoch 6/50
32/32 - 0s - loss: 1.0986 - accuracy: 0.3125 - 71ms/epoch - 2ms/step
Epoch 7/50
32/32 - 0s - loss: 1.0986 - accuracy: 0.3125 - 70ms/epoch - 2ms/step
Epoch 8/50
32/32 - 0s - loss: 1.0986 - accuracy: 0.3125 - 69ms/epoch - 2ms/step
Epoch 9/50
32/32 - 0s - loss: 1.0986 - accuracy: 0.3125 - 68ms/epoch - 2ms/step
Epoch 10/50
32/32 - 0s - loss: 1.0986 - accuracy: 0.3125 - 68ms/epoch - 2ms/step
Epoch 11/50
32/32 - 0s - loss: 1.0986 - accuracy: 0.3125 - 68ms/epoch - 2ms/step
Epoch 12/50
32/32 - 0s - loss: 1.0986 - accuracy: 0.3125 - 67ms/epoch - 2ms/step
Epoch 13/50
32/32 - 0s - loss: 1.09

In [37]:
np.nan == np.nan

False

In [6]:
# mask_value= [np.nan, np.nan]

In [7]:
# X_padded= []
# for i in range(100):
#     X_ = []
#     pad = max_len - seq_lengths[i]
#     X_ = [p for p in X[i]]
#     for _ in range(pad):
#         X_.append(mask_value)
#     X_padded.append(X_)

# # X_padded = tf.expand_dims(X_padded, axis=-1)
# # # X_padded = np.array(X_padded)
# # X_padded.shape

In [8]:
X_padded = np.expand_dims(X_padded, axis=-1)

In [23]:
# X_padded.shape

(100, 49, 2, 1)

In [13]:
# model = Sequential()
# model.add(layers.Masking(mask_value=mask_value, input_shape=(49, 1)))
# model.add(layers.SimpleRNN(units=16))
# model.add(layers.Dense(units=1, activation='sigmoid'))
# inputs = Input(shape=(49,2))
# x = layers.Masking(mask_value=np.nan, input_shape=(49,2))(inputs)
# x = layers.SimpleRNN(units=16)(x)
# x = layers.Dense(units=2, activation="sigmoid")(x)
# model = Model(inputs=inputs, outputs=x)
# model.summary()

Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 49, 2)]           0         
                                                                 
 masking_1 (Masking)         (None, 49, 2)             0         
                                                                 
 simple_rnn_2 (SimpleRNN)    (None, 16)                304       
                                                                 
 dense_1 (Dense)             (None, 2)                 34        
                                                                 
Total params: 338
Trainable params: 338
Non-trainable params: 0
_________________________________________________________________


In [14]:
# model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [15]:
# model(X_padded)

<tf.Tensor: shape=(100, 2), dtype=float32, numpy=
array([[       nan,        nan],
       [       nan,        nan],
       [       nan,        nan],
       [       nan,        nan],
       [       nan,        nan],
       [       nan,        nan],
       [0.56388193, 0.4953467 ],
       [       nan,        nan],
       [       nan,        nan],
       [       nan,        nan],
       [0.53903973, 0.49090222],
       [       nan,        nan],
       [       nan,        nan],
       [       nan,        nan],
       [       nan,        nan],
       [       nan,        nan],
       [       nan,        nan],
       [       nan,        nan],
       [       nan,        nan],
       [       nan,        nan],
       [       nan,        nan],
       [       nan,        nan],
       [       nan,        nan],
       [       nan,        nan],
       [       nan,        nan],
       [       nan,        nan],
       [       nan,        nan],
       [       nan,        nan],
       [       nan,       

In [12]:
# model.fit(X_padded, Y, batch_size=1, epochs=50, sample_weight=seq_lengths)

Epoch 1/50


2023-05-09 23:53:26.941040: W tensorflow/tsl/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


100/100 [==============================] - 1s 2ms/step - loss: nan - accuracy: 0.4100
Epoch 2/50
100/100 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.4100
Epoch 3/50
100/100 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.4100
Epoch 4/50
100/100 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.4100
Epoch 5/50
100/100 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.4100
Epoch 6/50
100/100 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.4100
Epoch 7/50
100/100 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.4100
Epoch 8/50
100/100 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.4100
Epoch 9/50
100/100 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.4100
Epoch 10/50
100/100 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.4100
Epoch 11/50
100/100 [===================

In [79]:
np.nan == np.nan

False